version: "3.9"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    env_file:
      - .env
  app:
    build: .
    command: >
      sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/api
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres-data:
